version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
      - '8099:8099'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - JVMFLAGS="-Dzookeeper.admin.serverPort=8099" # Change Zookeeper port. Default is 8080.
    network_mode: "host"

  kafka1:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      # Why use ${DOCKERHOST}: Internal host wrong: https://github.com/wurstmeister/kafka-docker/issues/17#issuecomment-370237590
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_PORT: 9092
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_CFG_ADVERTISED_PORT: 9092
      KAFKA_CFG_ADVERTISED_HOST_NAME: "${DOCKERHOST}"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://${DOCKERHOST}:9092"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "${DOCKERHOST}:2181"
      KAFKA_CFG_LOG_RETENTION_BYTES: 10485760 # 10 mb
      KAFKA_CFG_LOG_RETENTION_HOURS: 8
    depends_on:
      - zookeeper
    network_mode: "host"
    extra_hosts:
      - "dockerhost:$DOCKERHOST"

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_VHOST: kafka-streams-order-app
    network_mode: "host"
    extra_hosts:
      - "dockerhost:$DOCKERHOST"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local